# Generated by Django 4.1.7 on 2023-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_date_created_document_date_uploaded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_uploaded',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='document',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='document',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
