# Generated by Django 4.1.7 on 2023-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_dossier_document_dossier_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='labels',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentLabel',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
